routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get(config('app.blog_url_prefix'), function(){})->name('blog');

Route::get('privacy', 'HomeController@privacyPage')->name('privacy');

Route::post('/commission/LiqPay', 'PaymentController@handleLiqPayCallback')->name('liqpay.callback');

Route::get('/commission/pay/order/{orderId}', 'PaymentController@initTransaction')->name('commission.pay.order');

Route::group(['namespace' => 'Auth'], function () {

    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::get('email-verification/check/{token}', 'RegisterController@getVerification')->name('email-verification.check');

    Route::group(['middleware' => ['guest']], function () {
        // Authentication Routes...
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');
        // Registration Routes...
        Route::get('client/register', 'RegisterController@showRegisterClientForm')->name('client.register');
        Route::post('client/register', 'RegisterController@clientCreate');
        Route::post('client/facebook/register', 'RegisterController@facebookClientCreate')->name('client.facebook.register');
        Route::post('master/facebook/register', 'RegisterController@facebookMasterCreate')->name('master.facebook.register');
        Route::get('master/register', 'RegisterController@showRegistrationForm')->name('master.register');
        Route::post('master/register', 'RegisterController@masterCreate');

        Route::get('registration', function () {
            return view('auth.facebook_wrong_login');
        })->name('registration');

        // Password Reset Routes...
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset');
    });

    Route::get('password/reset/{token?}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
    Route::get('password/change', 'ResetPasswordController@showChangeForm')->name('password.change')->middleware('role:admin,client,master,distributor');
    Route::post('password/change', 'ResetPasswordController@change')->name('password.change')->middleware('role:admin,client,master,distributor');

//client creation
    Route::post('user/MyProjects', 'RegisterController@clientCreate')->name('clientCreation');

    Route::group(['prefix' => 'facebook', 'as' => 'facebook.'], function () {

        Route::get('login/', 'OAuthController@facebookLogin')->name('login');
        Route::get('callback', 'OAuthController@facebookLoginCallback')->name('login.callback');
        Route::get('client/', 'RegisterController@facebookClient')->name('client');
        Route::get('master/', 'RegisterController@facebookMaster')->name('master');

        Route::get('attach', 'OAuthController@facebookAttach')->name('attach');
        Route::get('detach', 'OAuthController@facebookDetach')->name('detach');

    });

});

//TODO: change all routes below
Route::group(['middleware' => 'role:client,guest'], function() {
//    steps for creating an order
    Route::get('/user/search', function () {
        return view('temp.search');
    })->name('temp.search');
    Route::get('/user/search/step1', function () {
        return view('temp.step1');
    })->name('temp.step1');
    Route::get('/user/search/step2', function () {
        return view('temp.step2');
    })->name('temp.step2');
    Route::get('/user/search/step22', function () {
        return view('temp.step22');
    })->name('temp.step22');

//    assistant pages
    Route::get('/start', function () {
        return view('temp.step0');
    })->name('temp.step0');
    Route::group(['prefix' => 'faq'], function () {
        Route::get('', function () {
            return view('temp.faq');
        })->name('temp.faq');

        Route::get('/domashni_ses', function () {
            return view('temp.step2_1');
        })->name('assistant.step2_1');

        Route::get('/ses_na_bahatopoverkhivkakh', function () {
            return view('temp.step2_2');
        })->name('assistant.step2_2');

        Route::get('/nazemna_ses', function () {
            return view('temp.step2_3');
        })->name('assistant.step2_3');

        Route::get('/dakhova_ses_dlja_biznesu', function () {
            return view('temp.step2_4');
        })->name('assistant.step2_4');

        Route::get('/ses_dlja_shkil_likaren', function () {
            return view('temp.step2_4');
        });

        Route::get('/investycii_u_sonjachnu_energetyku', function () {
            return view('temp.step2_5');
        })->name('assistant.step2_5');

        Route::get('/ses_dlja_shkil_likaren', function () {
            return view('temp.step2_6');
        })->name('assistant.step2_6');
    });

//    station info
    Route::group(['prefix' => 'assistant', 'as' => 'assistant.'], function () {
        Route::get('merezheva-info', function () {
            return view('order.station-info-category.station-info-subcategory.network');
        })->name('network');

        Route::get('/avtonomna-info', function () {
            return view('order.station-info-category.station-info-subcategory.autonomous');
        })->name('autonomous');

        Route::get('/gibrydna-info', function () {
            return view('order.station-info-category.station-info-subcategory.hybrid');
        })->name('hybrid');

        Route::get('/nazemna-info', function () {
            return view('order.station-info-category.station-info-subcategory.ground');
        })->name('ground');

        Route::get('/dakhova-info', function () {
            return view('order.station-info-category.station-info-subcategory.roof');
        })->name('roof');
    });

    Route::get('services/consulting', function () {
        return view('temp.consulting');
    })->name('services.consulting');

    Route::post('services/consulting', 'HomeController@sendConsultingMail')->name('consulting.mail');
});
//TODO: change all routes under

Route::get('order/calculator', function (){
    return view('order.calculator');
})->name('order.calculator')->middleware('role:admin,client,guest');


Route::get('cancel_mailing/{order}/{token?}', 'Client\ClientController@cancelMailing')->name('cancel_mailing')->middleware('role:client,guest');
Route::get('confirm_mailing/{order}/{token?}', 'Client\ClientController@confirmMailing')->name('confirm_mailing')->middleware('role:client,guest');

Route::resource('order', 'OrderController', ['only' => ['show']]);

Route::group(['prefix' => 'brand', 'as' => 'brand.', 'namespace' => 'Equipment'], function () {
    Route::get('{equipment_type}', 'EquipmentController@index')->name('index')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::post('{equipment_type}', 'EquipmentController@index')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}', 'EquipmentController@show')->name('show')
        ->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}/review/create', 'EquipmentReviewController@create')
        ->name('review.create')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}/review/{id}/edit', 'EquipmentReviewController@edit')
        ->name('review.edit')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::resource('review', 'EquipmentReviewController', ['except' => [ 'create', 'edit', 'index' ]]);
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'role:admin'], function () {


    Route::get('portfolio/photo/minimize', 'MasterPortfolioController@minimizePhoto');
//    admin.order.index page request based filtering
    Route::post('order/photo/delete', 'OrderController@deletePhoto')->name('order.photo.delete');

    Route::get('order/activate/{id}', 'OrderController@activate')->name('order.activate');

    Route::post('order/attachment/upload', 'OrderController@attachmentUpload')->name('attachment.upload');

    Route::post('/order/attachment/upload/completed', 'OrderController@finishUploadSession')->name('attachment.upload.complete');
    
    Route::post('order', 'OrderController@index')->name('order.index.filter');

    Route::post('order/{id}/subcategory/change', 'OrderController@changeCategory')->name('order.category.change');

    Route::get('order/{id}/request', 'OrderController@requests')->name('order.request');

    Route::put('order/{id}/meta', 'OrderController@updateMeta')->name('order.update.meta');

    Route::resource('order', 'OrderController', [
        'except' => ['create', 'store', 'destroy']
    ]);

    Route::resource('request', 'OrderRequestController', [
        'only' => ['edit', 'update']
    ]);

    Route::resource('preorder', 'PreorderController', ['only' => ['index', 'update']]);


    Route::resource('client_email', 'ClientEmailController', ['only' => ['index', 'update']]);

    Route::get('client_catalog_list', 'ClientEmailController@showCatalog')->name('client_catalog_list');

    Route::put('client_catalog_list/{id}', 'ClientEmailController@updateCatalog')->name('update_catalog');

//      admin.equipment.index page request based filtering
    Route::resource('equipment', 'EquipmentController', ['only' => ['index']]);

    Route::group(['prefix' => 'equipment', 'as' => 'equipment.'], function () {
        Route::post('', 'EquipmentController@index')->name('index.filter');

        Route::get('create', 'EquipmentController@create')->name('create');

        Route::post('store', 'EquipmentController@store')->name('store');

resources/views/order/station-info-category/station-info-subcategory/autonomous.blade.php
@extends('order.station-info-category.station-home')

@section('station-title', 'автономна')

@section('station-cost-depends')
    Вартість автономної станції залежить від <b>потужності та ємності акумуляторів.</b>
@endsection

@section('slider-power')
    <div class="slider-block power-station" >
        <div id="power-auto-station" data-min="1" data-max="30"></div>
        <!-- /#power-station -->
    </div>
    <p class="title">Ємність акумуляторів:</p>
    <!-- /.title -->
    <div class="slider-block capacity-slider">
        <div id="capacity-slider" data-min="0" data-max="100"></div>
        <!-- /#capacity-slider -->
    </div>
    <!-- /.slider-block -->
    <p class="info">
        Не знаєте, яка потужність та ємінсть акумуляторів вам потрібно? <a href="{{ route('order.calculator') }}">Вам допоможе цей
            калькулятор.</a>
    </p>
@endsection

@section('station-link')
    <p>Якщо ви вважаєте, що вам не потрібні акумулятори, то можете перейти на сторінку з інформацією про
        <a href="{{ route('assistant.network') }}">мережеві сонячні електростанції</a></p>
@endsection

@section('ses-link')
    <li>
        <a href="{{ route('client.order.create', ['category' => 'ses', 'subcategory' => 'autonomous']) }}" class="choise-check">
            <img src="{{ asset('images/check.png') }}">
            Хочу дізнатися точну ціну на автономну станцію для мого будинку</a></li>
@endsection

@section('consult-link')
    <li><a href="{{ route('services.consulting') }}"><img src="{{asset('images/chat-message.png')}}" alt=""> Замовити послуги персонального консультанта</a></li>
@endsection

@section('site-title', 'Скільки коштує автономна сонячна електростанція під ключ для продажу енергії по “зеленому” тарифу - калькулятор, ціни, виробіток')

resources/views/order/station-info-category/station-info-subcategory/ground.blade.php
@extends('order.station-info-category.station-commercial')

@section('station-title', 'наземна комерційна')

@section('station-cost-depends')
    Вартість наземної станції залежить від <b>потужності.</b>
@endsection

@section('slider-power')
    <div class="slider-block power-station">
        <div id="power-ground-station" data-min="150" data-max="10000"></div>
        <!-- /#power-station -->
    </div>
@endsection

@section('station-type-photo')
    <img src="{{ asset('images/area.png') }}" alt="image">
@endsection

@section('station-area-type', 'ділянки')

@section('tooltip-text', 'Для будівництва СЕС потрібно попередньо змінити цільове призначення земельної ділянки')

@section('station-max-income')
    <div class="param-item">
        <img src="{{ asset('images/income.png') }}" alt="image">
        <p>
            Максимальний дохід за рік:
        </p>
        <strong>$2 000</strong>
        <span>(Якщо власне споживання = 0)</span>
    </div>
@endsection

@section('station-faq-info')
    <div class="station-info-block left-image right-arrow">
        <div class="station-info-img">
            <img src="{{ asset('images/sun-station.png') }}" alt="image">
        </div>
        <!-- /.station-info-img -->
        <h2>Чому наземні комерційні станції такі дорогі?</h2>
        <p>
            Основна причина, чому комерційні станції дорожчі від домашніх - це необхідність проходження багатьох бюрократичних процедур для отримання "зеленого" тарифу.
            <br><br>
            Саме тому назумні комерційні станції варто будувати потужністю від 200 кВт.<br><br>
            При цьому варто пам'ятати, що для будівництва комерційних станцій можна отримати дуже хороші
            умови кредитування.
        </p>
    </div>
@endsection

@section('ses-link')
    <li><a href="{{ route('client.order.create', ['category' => 'ses', 'subcategory' => 'commercial', 'ground' => 'ground']) }}" class="choise-check">
            <img src="{{ asset('images/check.png') }}">
            Хочу дізнатися точну ціну на наземну комерційну станцію</a></li>
@endsection

@section('consult-link')
    <li><a href="{{ route('services.consulting') }}"><img src="{{asset('images/chat-message.png')}}" alt=""> Замовити послуги персонального консультанта</a></li>
@endsection

@section('site-title', 'Скільки коштує наземна комерційна сонячна електростанція під ключ для продажу енергії по “зеленому” тарифу - калькулятор, ціни, виробіток')

resources/views/order/station-info-category/station-info-subcategory/hybrid.blade.php
@extends('order.station-info-category.station-home')

@section('station-title', 'гібридна')

@section('station-cost-depends')
    Вартість гібридної станції залежить від <b>потужності та ємності акумуляторів.</b>
@endsection

@section('slider-power')
    <div class="slider-block power-station" >
        <div id="power-hybrid-station" data-min="3" data-max="30"></div>
        <!-- /#power-station -->
    </div>
    <p class="title">Ємність акумуляторів:</p>
    <!-- /.title -->
    <div class="slider-block capacity-slider">
        <div id="capacity-slider" data-min="0" data-max="100"></div>
        <!-- /#capacity-slider -->
    </div>
    <!-- /.slider-block -->
    <p class="info">
        Не знаєте, яка потужність та ємінсть акумуляторів вам потрібно? <a href="{{ route('order.calculator') }}">Вам допоможе цей
            калькулятор.</a>
    </p>
@endsection

@section('station-max-income')
    <div class="param-item">
        <img src="{{ asset('images/income.png') }}" alt="image">
        <p>
            Максимальний дохід за рік:
        </p>
        <strong class="max-income">&euro;2 000</strong>
        <span>(Якщо власне споживання = 0)</span>
    </div>
@endsection

@section('alert')
    <div class="alert alert-danger">
        <b>Увага!</b> Тут дуже приблизні дані щодо доходів. Якщо у вас споживання та виробіток станції будуть
        однакові, то чистих доходів така
        станція не принесе, а лише дозволить економити.
    </div>
@endsection

@section('station-link')
    <p>Якщо ви вважаєте, що вам не потрібні акумулятори, то можете перейти на сторінку з інформацією про
        <a href="{{ route('assistant.network') }}">мережеві сонячні електростанції</a></p>
@endsection

@section('ses-link')
    <li><a href="{{ route('client.order.create', ['category' => 'ses', 'subcategory' => 'hybrid']) }}" class="choise-check">
            <img src="{{ asset('images/check.png') }}">
            Хочу дізнатися точну ціну на гібридну станцію для мого будинку</a></li>
@endsection

@section('consult-link')
    <li><a href="{{ route('services.consulting') }}"><img src="{{asset('images/chat-message.png')}}" alt=""> Замовити послуги персонального консультанта</a></li>
@endsection

@section('site-title', 'Скільки коштує гібридна сонячна електростанція під ключ для продажу енергії по “зеленому” тарифу - калькулятор, ціни, виробіток')

resources/views/order/station-info-category/station-info-subcategory/network.blade.php
@extends('order.station-info-category.station-home')

@section('station-class', 'network-station')

@section('station-title', 'мережева')

@section('station-cost-depends')
    Вартість мережевої станції в першу чергу залежить від <b>потужності.</b>
@endsection

@section('station-methods-calc')
    <p class="info">А розрахувати необхідну потужність можна декількома способами:</p>
    <ol class="calculation-info">
        <li><span>1.</span> в залежності від того, яку суму ви можете інвестувати;</li>
        <li><span>2.</span> в залежності від площі даху/подвір'я, де ви можете розмістити станцію.</li>
    </ol>
    <p class="info">Скористайтеся калькулятором нижче, щоб приблизно зрозуміти яка потужність станції вам потрібна:</p>
@endsection

@section('slider-power')
    <div class="slider-block power-station" >
        <div id="power-network-station" data-min="3" data-max="30"></div>
        <!-- /#power-station -->
    </div>
@endsection

@section('station-max-income')
    <div class="param-item">
        <img src="{{ asset('images/income.png') }}" alt="image">
        <p>
            Максимальний дохід за рік:
        </p>
        <strong class="max-income">&euro;2 000</strong>
        <span>(Якщо власне споживання = 0)</span>
    </div>
@endsection

@section('alert')
    <div class="alert alert-danger">
        <b>Увага!</b> Тут дуже приблизні дані щодо доходів. Якщо у вас споживання та виробіток станції будуть
        однакові, то чистих доходів така
        станція не принесе, а лише дозволить економити.
    </div>
@endsection

@section('station-link')
    <p>Якщо ви вважаєте, що вам потрібні акумулятори (та заробіток на "зеленому" тарифі), то вам потрібна
        <a href="{{ route('assistant.hybrid') }}">гібридна сонячна електростанція</a>.</p>
@endsection

@section('ses-link')
    <li><a href="{{ route('client.order.create', ['category' => 'ses', 'subcategory' => 'network']) }}" class="choise-check">
            <img src="{{ asset('images/check.png') }}">
            Хочу дізнатися точну ціну на мережеву станцію для мого будинку</a></li>
@endsection

@section('consult-link')
    <li><a href="{{ route('services.consulting') }}"><img src="{{asset('images/chat-message.png')}}" alt=""> Замовити послуги персонального консультанта</a></li>
@endsection

@section('site-title', 'Скільки коштує мережева сонячна електростанція під ключ для продажу енергії по “зеленому” тарифу - калькулятор, ціни, виробіток')

resources/views/order/station-info-category/station-info-subcategory/roof.blade.php
@extends('order.station-info-category.station-commercial')

@section('station-title', 'дахова комерційна')

@section('station-cost-depends')
    Вартість дахової станції залежить від <b>потужності.</b>
@endsection

@section('slider-power')
    <div class="slider-block power-station">
        <div id="power-roof-station" data-min="60" data-max="1000"></div>
        <!-- /#power-station -->
    </div>
@endsection

@section('station-type-photo')
    <img style="margin-bottom: 9px" src="{{ asset('images/roof.png') }}" alt="image">
@endsection

@section('station-area-type', 'даху')

@section('tooltip-text', 'Площа розрахована для плаского даху із незначними затіненнями від димарів/витяжок. Якщо ж у вас похилий дах на Південну сторону, то вам для цієї потужності знадобиться в 2 або в 3 рази менша площа')

@section('station-max-income')
    <div class="param-item">
        <img src="{{ asset('images/income.png') }}" alt="image">
        <p>
            Максимальний дохід за рік:
        </p>
        <strong>$2 000</strong>
        <span>(Якщо власне споживання = 0)</span>
    </div>
@endsection

@section('station-faq-info')
    <div class="station-info-block left-image right-arrow">
        <div class="station-info-img">
            <img src="{{ asset('images/roof-station.png') }}" alt="image">
        </div>
        <!-- /.station-info-img -->
        <h2>Чому дахові комерційні станції такі дорогі?</h2>
        <p>
            Основна причина, чому комерційні станції дорожчі від домашніх - це необхідність проходження багатьох бюрократичних процедур для отримання "зеленого" тарифу.
            <br><br>
            Саме тому дахові комерційні станції варто будувати потужністю від 100 кВт.<br><br>
            При цьому варто пам'ятати, що для будівництва комерційних станцій можна отримати дуже хороші
            умови кредитування.
        </p>
    </div>
@endsection

@section('ses-link')
    <li><a href="{{ route('client.order.create', ['category' => 'ses', 'subcategory' => 'commercial', 'ground' => 'roof']) }}" class="choise-check">
            <img src="{{ asset('images/check.png') }}">
            Хочу дізнатися точну ціну на дахову комерційну станцію для мого приміщення</a></li>
@endsection

@section('site-title', 'Скільки коштує дахова комерційна сонячна електростанція під ключ для продажу енергії по “зеленому” тарифу - калькулятор, ціни, виробіток')