routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get(config('app.blog_url_prefix'), function(){})->name('blog');

Route::get('privacy', 'HomeController@privacyPage')->name('privacy');

Route::post('/commission/LiqPay', 'PaymentController@handleLiqPayCallback')->name('liqpay.callback');

Route::get('/commission/pay/order/{orderId}', 'PaymentController@initTransaction')->name('commission.pay.order');

Route::group(['namespace' => 'Auth'], function () {

    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::get('email-verification/check/{token}', 'RegisterController@getVerification')->name('email-verification.check');

    Route::group(['middleware' => ['guest']], function () {
        // Authentication Routes...
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');
        // Registration Routes...
        Route::get('client/register', 'RegisterController@showRegisterClientForm')->name('client.register');
        Route::post('client/register', 'RegisterController@clientCreate');
        Route::post('client/facebook/register', 'RegisterController@facebookClientCreate')->name('client.facebook.register');
        Route::post('master/facebook/register', 'RegisterController@facebookMasterCreate')->name('master.facebook.register');
        Route::get('master/register', 'RegisterController@showRegistrationForm')->name('master.register');
        Route::post('master/register', 'RegisterController@masterCreate');

        Route::get('registration', function () {
            return view('auth.facebook_wrong_login');
        })->name('registration');

        // Password Reset Routes...
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset');
    });

    Route::get('password/reset/{token?}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
    Route::get('password/change', 'ResetPasswordController@showChangeForm')->name('password.change')->middleware('role:admin,client,master,distributor');
    Route::post('password/change', 'ResetPasswordController@change')->name('password.change')->middleware('role:admin,client,master,distributor');

//client creation
    Route::post('user/MyProjects', 'RegisterController@clientCreate')->name('clientCreation');

    Route::group(['prefix' => 'facebook', 'as' => 'facebook.'], function () {

        Route::get('login/', 'OAuthController@facebookLogin')->name('login');
        Route::get('callback', 'OAuthController@facebookLoginCallback')->name('login.callback');
        Route::get('client/', 'RegisterController@facebookClient')->name('client');
        Route::get('master/', 'RegisterController@facebookMaster')->name('master');

        Route::get('attach', 'OAuthController@facebookAttach')->name('attach');
        Route::get('detach', 'OAuthController@facebookDetach')->name('detach');

    });

});

//TODO: change all routes below
Route::group(['middleware' => 'role:client,guest'], function() {
//    steps for creating an order
    Route::get('/user/search', function () {
        return view('temp.search');
    })->name('temp.search');
    Route::get('/user/search/step1', function () {
        return view('temp.step1');
    })->name('temp.step1');
    Route::get('/user/search/step2', function () {
        return view('temp.step2');
    })->name('temp.step2');
    Route::get('/user/search/step22', function () {
        return view('temp.step22');
    })->name('temp.step22');

//    assistant pages
    Route::get('/start', function () {
        return view('temp.step0');
    })->name('temp.step0');
    Route::group(['prefix' => 'faq'], function () {
        Route::get('', function () {
            return view('temp.faq');
        })->name('temp.faq');

        Route::get('/domashni_ses', function () {
            return view('temp.step2_1');
        })->name('assistant.step2_1');

        Route::get('/ses_na_bahatopoverkhivkakh', function () {
            return view('temp.step2_2');
        })->name('assistant.step2_2');

        Route::get('/nazemna_ses', function () {
            return view('temp.step2_3');
        })->name('assistant.step2_3');

        Route::get('/dakhova_ses_dlja_biznesu', function () {
            return view('temp.step2_4');
        })->name('assistant.step2_4');

        Route::get('/ses_dlja_shkil_likaren', function () {
            return view('temp.step2_4');
        });

        Route::get('/investycii_u_sonjachnu_energetyku', function () {
            return view('temp.step2_5');
        })->name('assistant.step2_5');

        Route::get('/ses_dlja_shkil_likaren', function () {
            return view('temp.step2_6');
        })->name('assistant.step2_6');
    });

//    station info
    Route::group(['prefix' => 'assistant', 'as' => 'assistant.'], function () {
        Route::get('merezheva-info', function () {
            return view('order.station-info-category.station-info-subcategory.network');
        })->name('network');

        Route::get('/avtonomna-info', function () {
            return view('order.station-info-category.station-info-subcategory.autonomous');
        })->name('autonomous');

        Route::get('/gibrydna-info', function () {
            return view('order.station-info-category.station-info-subcategory.hybrid');
        })->name('hybrid');

        Route::get('/nazemna-info', function () {
            return view('order.station-info-category.station-info-subcategory.ground');
        })->name('ground');

        Route::get('/dakhova-info', function () {
            return view('order.station-info-category.station-info-subcategory.roof');
        })->name('roof');
    });

    Route::get('services/consulting', function () {
        return view('temp.consulting');
    })->name('services.consulting');

    Route::post('services/consulting', 'HomeController@sendConsultingMail')->name('consulting.mail');
});
//TODO: change all routes under

Route::get('order/calculator', function (){
    return view('order.calculator');
})->name('order.calculator')->middleware('role:admin,client,guest');


Route::get('cancel_mailing/{order}/{token?}', 'Client\ClientController@cancelMailing')->name('cancel_mailing')->middleware('role:client,guest');
Route::get('confirm_mailing/{order}/{token?}', 'Client\ClientController@confirmMailing')->name('confirm_mailing')->middleware('role:client,guest');

Route::resource('order', 'OrderController', ['only' => ['show']]);

Route::group(['prefix' => 'brand', 'as' => 'brand.', 'namespace' => 'Equipment'], function () {
    Route::get('{equipment_type}', 'EquipmentController@index')->name('index')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::post('{equipment_type}', 'EquipmentController@index')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}', 'EquipmentController@show')->name('show')
        ->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}/review/create', 'EquipmentReviewController@create')
        ->name('review.create')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}/review/{id}/edit', 'EquipmentReviewController@edit')
        ->name('review.edit')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::resource('review', 'EquipmentReviewController', ['except' => [ 'create', 'edit', 'index' ]]);
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'role:admin'], function () {


    Route::get('portfolio/photo/minimize', 'MasterPortfolioController@minimizePhoto');
//    admin.order.index page request based filtering
    Route::post('order/photo/delete', 'OrderController@deletePhoto')->name('order.photo.delete');

    Route::get('order/activate/{id}', 'OrderController@activate')->name('order.activate');

    Route::post('order/attachment/upload', 'OrderController@attachmentUpload')->name('attachment.upload');

    Route::post('/order/attachment/upload/completed', 'OrderController@finishUploadSession')->name('attachment.upload.complete');
    
    Route::post('order', 'OrderController@index')->name('order.index.filter');

    Route::post('order/{id}/subcategory/change', 'OrderController@changeCategory')->name('order.category.change');

    Route::get('order/{id}/request', 'OrderController@requests')->name('order.request');

    Route::put('order/{id}/meta', 'OrderController@updateMeta')->name('order.update.meta');

    Route::resource('order', 'OrderController', [
        'except' => ['create', 'store', 'destroy']
    ]);

    Route::resource('request', 'OrderRequestController', [
        'only' => ['edit', 'update']
    ]);

    Route::resource('preorder', 'PreorderController', ['only' => ['index', 'update']]);


    Route::resource('client_email', 'ClientEmailController', ['only' => ['index', 'update']]);

    Route::get('client_catalog_list', 'ClientEmailController@showCatalog')->name('client_catalog_list');

    Route::put('client_catalog_list/{id}', 'ClientEmailController@updateCatalog')->name('update_catalog');

//      admin.equipment.index page request based filtering
    Route::resource('equipment', 'EquipmentController', ['only' => ['index']]);

    Route::group(['prefix' => 'equipment', 'as' => 'equipment.'], function () {
        Route::post('', 'EquipmentController@index')->name('index.filter');

        Route::get('create', 'EquipmentController@create')->name('create');

        Route::post('store', 'EquipmentController@store')->name('store');

app/Models/Order/Request/OrderRequestPrice.php
<?php

/**
 * Created by Reliese Model.
 * Date: Wed, 17 May 2017 13:24:33 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class OrderRequestPrice
 * 
 * @property int $id
 * @property int $request_id
 * @property int $type_id
 * @property float $price
 * @property string $comment
 * 
 * @property \App\Models\OrderRequest $order_request
 * @property \App\Models\OrderRequestPriceType $type
 *
 * @package App\Models
 */
class OrderRequestPrice extends Eloquent
{
	public $timestamps = false;

	protected $casts = [
		'request_id' => 'int',
		'type_id' => 'int',
		'price' => 'float'
	];

	protected $fillable = [
		'request_id',
		'type_id',
		'price',
		'comment'
	];

	public function order_request()
	{
		return $this->belongsTo(\App\Models\OrderRequest::class, 'request_id');
	}

	public function type()
	{
		return $this->belongsTo(\App\Models\OrderRequestPriceType::class, 'type_id');
	}
}

app/Models/Order/Request/OrderRequestPriceType.php
<?php

/**
 * Created by Reliese Model.
 * Date: Wed, 17 May 2017 13:24:33 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class OrderRequestPriceType
 * 
 * @property int $id
 * @property int $category_id
 * @property string $name
 * @property string $description
 * @property string $slug
 * 
 * @property \App\Models\OrderCategory $category
 * @property \Illuminate\Database\Eloquent\Collection $prices
 *
 * @package App\Models
 */
class OrderRequestPriceType extends Eloquent
{
	public $timestamps = false;

	protected $casts = [
		'category_id' => 'int'
	];

	protected $fillable = [
		'category_id',
		'name',
		'description',
		'slug'
	];

	public function category()
	{
		return $this->belongsTo(\App\Models\OrderCategory::class, 'category_id');
	}

	public function prices()
	{
		return $this->hasMany(\App\Models\OrderRequestPrice::class, 'type_id');
	}

	public function orders()
    {
        return $this->belongsToMany(\App\Models\Order::class, 'order_price_type_pivot', 'order_id', 'price_type_id');
    }
}

app/Models/SubcategoryFactor.php
<?php

/**
 * Created by Reliese Model.
 * Date: Wed, 17 May 2017 13:24:34 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class OrderSubcategory
 *
 * @property int $id
 * @property int $category_id
 * @property string $name
 * @property string $slug
 *
 * @property \App\Models\OrderCategory $category
 * @property \Illuminate\Database\Eloquent\Collection $orders
 * @property \Illuminate\Database\Eloquent\Collection $partners
 *
 * @package App\Models
 */
//TODO: move this class to Order directory and Order namespace
class SubcategoryFactor extends Eloquent
{
    public $timestamps = false;

    protected $casts = [
        'subcategory_id' => 'int'
    ];

    protected $fillable = [
        'subcategory_id',
        'factor'
    ];

    public function subcategory()
    {
        return $this->belongsTo(\App\Models\OrderSubcategory::class, 'subcategory_id');
    }
    
    public function getPercentsAttribute()
    {
        return $this->factor * 100;
    }
}

app/Http/Controllers/Master/OrderController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller as Controller;
use App\Models\Order;
use App\Models\OrderRequest;
use App\Repositories\Criteria\Order\HomeSes;
use App\Repositories\Criteria\Order\InMastersRegions;
use App\Repositories\Criteria\Order\MasterList;
use App\Repositories\Criteria\Order\MasterListPrivate;
use App\Repositories\Criteria\RelationAttribute;
use App\Repositories\OrderRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{

    protected $orderRepository;

    public function __construct(OrderRepository $orderRepository)
    {
        $this->middleware('commission');

        $this->orderRepository = $orderRepository;
    }

    /**
     * Display a list of orders.
     *
     * @param  string $filter
     * @return \Illuminate\Http\Response
     */
    public function index($filter = null)
    {
        $master_id = Auth::user()->master->id;
        $master = Auth::user()->master;
        $this->orderRepository->pushCriteria(new MasterList($master_id));

        if($master->getSesTypes() == 'commercial_ses') {
            if($filter == 'region_filter_on') {
                $filter = 'commercial/region_filter_on';
            }
            else {
                $filter = 'commercial';
            }
        }
        else if($master->getSesTypes() == 'home_ses') {
            if($filter == 'region_filter_on') {
                $filter = 'home/region_filter_on';
            }
            else {
                $filter = 'home';
            }
        }
        if(!$this->orderRepository->validateUrlFilter($filter))
            abort(404);

        $filter = $this->orderRepository->decodeUrlFilter($filter);

        if(isset($filter['category']))
            $this->orderRepository->pushCriteria(new RelationAttribute('subcategory.category', 'slug', $filter['category']));

        if(isset($filter['subcategory']))
            $this->orderRepository->pushCriteria(new RelationAttribute('subcategory', 'slug', $filter['subcategory']));

        if(isset($filter['home']))
            $this->orderRepository->pushCriteria(new HomeSes('subcategory', 'slug', $filter['home']));

        if(isset($filter['region_filter_on']))
            $this->orderRepository->pushCriteria(new InMastersRegions($master_id));

        $orders = $this->orderRepository->paginate(20);

        return view('master.order.index', compact('orders', 'filter', 'master'));
    }

    /**
     * Display a list of orders where master selected as executor.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexPrivate()
    {
        $master_id = Auth::user()->master->id;

        $orders = $this->orderRepository->pushCriteria(new MasterListPrivate($master_id))->all();

        return view('master.order.private.index', compact('orders'));
    }

    /**
     * Display the specified order.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = $this->orderRepository->with(['subcategory.category', 'orderable', 'subcategory.category.request_price_types', 'status'])->findOrFail($id);

        if(Auth::user()->can('view', $order)){
            if(Auth::user()->can('own', $order))
                return redirect()->route('master.order.private.show', ['id' => $order->id]);

//            TODO: query in controller is not good (use request relation)
            $request = OrderRequest::with(['master' => function($master) {
                $master->withCount(['reviews', 'negative_reviews']);
            }, 'prices'])->where('master_id', Auth::user()->master->id)->where('order_id', $order->id)->first();

            if(isset($request)) {
                return view('master.request.show', compact('order', 'request'));
            } else {
                return view('master.request.create', compact('order'));
            }
        }else{
            return 'Проект закрито';
        }
    }

    /**
     * Display the specified order where master selected as executor.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showPrivate($id)
    {
        $order = Order::with([
            'subcategory.category',
            'orderable.order.region',
            'subcategory.category.request_price_types',
            'status',
            'region'
        ])->findOrFail($id);

        if(Auth::user()->can('own', $order)) {
            return view('master.order.private.show', compact('order'));
        } else {
            return 'Доступ заблоковано';
        }
    }
}

resources/views/master/request/create.blade.php
@extends('order.show')
@section('user-section')
    <div class="contentBlock">
        <div class="container">
            <h3>Подайте вашу заявку</h3>
            <div>
                <div id="setApplication">
                    <h4>Оцініть вартість по кожному пункту, який цікавить клієнта:</h4>
                    <form id="formsm" class="validate_form" action="{{ route('master.request.store') }}" method="POST">
                        <div>
                            <div>
                                {{ csrf_field() }}
                                <input type="hidden" value="{{ $order->id }}" name="order_id">
                                {{--TODO: add label output (nowhere to get it dymanically)--}}
                                {{--TODO: output only prices that correspond to order blocks--}}
                                @if($order->price_types)
                                    @foreach($order->price_types as $price_type)
                                        <div class="setApplicationBlock">
                                            <h5>{{ $price_type->name }}:</h5>
                                            <div class="clr">
                                                <div class="setApp-price">
                                                    <div class="label">Ціна</div>
                                                    <div class="field">
                                                        <input class="request_price only-number validate_number" id="devices_price" min="0" name="prices[{{ $price_type->id }}]" step="any" type="number" value=""> <strong><b>$</b></strong>
                                                    </div>
                                                </div>
                                                <div class="setApp-desc">
                                                    <div class="label">{{ $price_type->description }}</div>
                                                    <textarea name="comments[{{ $price_type->id }}]"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                @endif
                            </div>
                            {{--<div class="requestChoices">--}}

                                {{--<div id="" class="checkboxChoices clr">--}}
                                    {{--<input name="final" type="checkbox" id="isNegative" value="1">--}}
                                    {{--<label for="isNegative">--}}
                                        {{--<div class="clr">--}}
                                            {{--<span>Попередня заявка</span>--}}
                                            {{--<span>Остаточна заявка</span>--}}
                                        {{--</div>--}}
                                    {{--</label>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            {{--<!-- /.requestChoices -->--}}
                            {{--<div class="appDifference">--}}
                                {{--<a>Яка різниця між попереднєю та остаточною заявками</a>--}}
                                {{--<div class="appDiffDesc">--}}
                                    {{--<div>--}}
                                        {{--<strong>Попередню заявку</strong> вибирайте в тому випадку, якщо ви точно не впевнені у остаточній вартості або якщо у вас є запитання до клієнта.--}}
                                    {{--</div>--}}
                                    {{--<div>--}}
                                        {{--<strong>Остаточну заявку</strong> вибирайте тоді, коли ви вже узгодили з клієнтом всі питання і вже домовилися щодо остаточної ціни.”--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--</div>--}}

                            <div class="sumarnaVartist">
                                <h2 id="moneysum">Сумарна вартість: $<span class="request_price_sum"></span></h2>
                                <div>
                                    <div class="comissionBlock">
                                        {{--TODO: get subcategory factor--}}
                                        <a href="{{ route('master.commission') }}">Комісія сервісу</a> = {{ $order->subcategory->subcategoryFactor->percents }}%
                                        <a href="#" class="open_tooltip">
                                            <span class="tooltip_info">
                                                <p>Комісія сплачується після того, як клієнт повністю із вами розрахується і залишить вам позитивний відгук</p>
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="buttonsWrapper">
                                <input type="submit" value="Подати заявку" class="site_button-orange"/>
                                <a href="{{ route('master.order.index') }}" class="site_button-orange onlyBorder">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @push('footer_scripts')
        <script src="{{ asset('js/jquery-validation/jquery.validate.min.js') }}"></script>
        <script src="{{ asset('js/jquery-validation/additional-methods.min.js') }}"></script>
        <script src="{{ asset('js/jquery-validation/localization/messages_uk.js') }}"></script>
        <script type="text/javascript" src="{{ asset('js/master/request/create.js') }}"></script>

    @endpush

@endsection

resources/views/master/request/edit.blade.php
@extends('layouts.request.edit')

@section('request-edit-action', route('master.request.update', ['id' => $order_request->id]))

resources/views/master/request/show.blade.php
@extends('order.show')
@section('user-section')
    <div class="contentBlock listOfApp">
        <div class="container">

            @if(Auth::user()->master->status->slug == 'verified' && $order->show_phone == true && $order->master_id != Auth::user()->master->id)
            <div class="">
                <h3>Контакти клієнта</h3>
                <br>
                <div class="clientDatas">
                    <div>
                        <div class="site_icon-person"><strong>Ім’я: </strong>{{ $order->client->user->name }}</div>
                    </div>
                    <div>
                        <div class="site_icon-phone_gray"><strong>Телефон: </strong> {{ $order->client->user->phone }}</div>
                    </div>
                    <div>
                        <div class="site_icon-mail_gray"><strong>E-mail: </strong> <a href="mailto:{{ $order->client->user->email }}"> {{ $order->client->user->email }}</a></div>
                    </div>
                </div>
            </div>
            <br>
            @endif

            <h3>Ваша заявка</h3>
            <div>
                <div class="app-item">
                    <div class="app-item-author clr">
                        <div class="app-item-author_info clr">
                            <h3><a href="{{ route('master.show', ['id' => $request->master->id]) }}">{{ $request->master->user->name }}</a></h3>
                            <div class="app-item-reviews site_icon-reviews">Відгуків: <a href="{{ route('master.show.reviews', ['id' => $request->master->id]) }}" class="">{{ $request->master->reviews_count }}</a>
                                @if($request->master->negative_reviews_count > 0)
                                    <a href="{{ route('master.show.reviews', ['id' => $request->master->id]) }}" class="site_color-red" title="Негативні відгуки">(-{{ $request->master->negative_reviews_count }})</a>
                                @endif
                            </div>
                            <a href="{{ route('master.show', ['id' => $request->master->id]) }}" class="app-item-author_img">
                                <img src="{{ $request->master->getAvatarSrc() }}" alt="{{ $request->master->user->name }}">
                            </a>
                            {{--TODO: make url filter maker--}}
                            <div class="app-item-loc site_icon-location"><a href="{{ route('master.index') . '/' . $request->master->region->slug }}" title="Переглянути інших спеціалістів із цього регіону">
                                    {{ $request->master->main_office->address ? explode(',', $request->master->main_office->address)[0] : $request->master->region->name }}
                                </a></div>
                        </div>
                        <div class="app-item-price">{{ $request->final ? 'Остаточна заявка' : 'Попередня заявка' }} <span>${{ $request->price }}</span></div>
                    </div>
                    <div class="app-item-content">
                        @foreach($request->prices as $price)
                            <h4>{{ $price->type->name }}: ${{ $price->price }}</h4>
                            <p style="margin-left:40px;white-space:pre-wrap;">{!! nl2br(e($price->comment)) !!}</p>
                        @endforeach
                        <a href="{{ route('master.request.edit', ['id' => $request->id]) }}" class="site_button-orange button-small leaveFeedback">Редагувати заявку</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection