routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get(config('app.blog_url_prefix'), function(){})->name('blog');

Route::get('privacy', 'HomeController@privacyPage')->name('privacy');

Route::post('/commission/LiqPay', 'PaymentController@handleLiqPayCallback')->name('liqpay.callback');

Route::get('/commission/pay/order/{orderId}', 'PaymentController@initTransaction')->name('commission.pay.order');

Route::group(['namespace' => 'Auth'], function () {

    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::get('email-verification/check/{token}', 'RegisterController@getVerification')->name('email-verification.check');

    Route::group(['middleware' => ['guest']], function () {
        // Authentication Routes...
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');
        // Registration Routes...
        Route::get('client/register', 'RegisterController@showRegisterClientForm')->name('client.register');
        Route::post('client/register', 'RegisterController@clientCreate');
        Route::post('client/facebook/register', 'RegisterController@facebookClientCreate')->name('client.facebook.register');
        Route::post('master/facebook/register', 'RegisterController@facebookMasterCreate')->name('master.facebook.register');
        Route::get('master/register', 'RegisterController@showRegistrationForm')->name('master.register');
        Route::post('master/register', 'RegisterController@masterCreate');

        Route::get('registration', function () {
            return view('auth.facebook_wrong_login');
        })->name('registration');

        // Password Reset Routes...
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('password.reset');
    });

    Route::get('password/reset/{token?}', 'ResetPasswordController@showResetForm')->name('password.reset.form');
    Route::get('password/change', 'ResetPasswordController@showChangeForm')->name('password.change')->middleware('role:admin,client,master,distributor');
    Route::post('password/change', 'ResetPasswordController@change')->name('password.change')->middleware('role:admin,client,master,distributor');

//client creation
    Route::post('user/MyProjects', 'RegisterController@clientCreate')->name('clientCreation');

    Route::group(['prefix' => 'facebook', 'as' => 'facebook.'], function () {

        Route::get('login/', 'OAuthController@facebookLogin')->name('login');
        Route::get('callback', 'OAuthController@facebookLoginCallback')->name('login.callback');
        Route::get('client/', 'RegisterController@facebookClient')->name('client');
        Route::get('master/', 'RegisterController@facebookMaster')->name('master');

        Route::get('attach', 'OAuthController@facebookAttach')->name('attach');
        Route::get('detach', 'OAuthController@facebookDetach')->name('detach');

    });

});

//TODO: change all routes below
Route::group(['middleware' => 'role:client,guest'], function() {
//    steps for creating an order
    Route::get('/user/search', function () {
        return view('temp.search');
    })->name('temp.search');
    Route::get('/user/search/step1', function () {
        return view('temp.step1');
    })->name('temp.step1');
    Route::get('/user/search/step2', function () {
        return view('temp.step2');
    })->name('temp.step2');
    Route::get('/user/search/step22', function () {
        return view('temp.step22');
    })->name('temp.step22');

//    assistant pages
    Route::get('/start', function () {
        return view('temp.step0');
    })->name('temp.step0');
    Route::group(['prefix' => 'faq'], function () {
        Route::get('', function () {
            return view('temp.faq');
        })->name('temp.faq');

        Route::get('/domashni_ses', function () {
            return view('temp.step2_1');
        })->name('assistant.step2_1');

        Route::get('/ses_na_bahatopoverkhivkakh', function () {
            return view('temp.step2_2');
        })->name('assistant.step2_2');

        Route::get('/nazemna_ses', function () {
            return view('temp.step2_3');
        })->name('assistant.step2_3');

        Route::get('/dakhova_ses_dlja_biznesu', function () {
            return view('temp.step2_4');
        })->name('assistant.step2_4');

        Route::get('/ses_dlja_shkil_likaren', function () {
            return view('temp.step2_4');
        });

        Route::get('/investycii_u_sonjachnu_energetyku', function () {
            return view('temp.step2_5');
        })->name('assistant.step2_5');

        Route::get('/ses_dlja_shkil_likaren', function () {
            return view('temp.step2_6');
        })->name('assistant.step2_6');
    });

//    station info
    Route::group(['prefix' => 'assistant', 'as' => 'assistant.'], function () {
        Route::get('merezheva-info', function () {
            return view('order.station-info-category.station-info-subcategory.network');
        })->name('network');

        Route::get('/avtonomna-info', function () {
            return view('order.station-info-category.station-info-subcategory.autonomous');
        })->name('autonomous');

        Route::get('/gibrydna-info', function () {
            return view('order.station-info-category.station-info-subcategory.hybrid');
        })->name('hybrid');

        Route::get('/nazemna-info', function () {
            return view('order.station-info-category.station-info-subcategory.ground');
        })->name('ground');

        Route::get('/dakhova-info', function () {
            return view('order.station-info-category.station-info-subcategory.roof');
        })->name('roof');
    });

    Route::get('services/consulting', function () {
        return view('temp.consulting');
    })->name('services.consulting');

    Route::post('services/consulting', 'HomeController@sendConsultingMail')->name('consulting.mail');
});
//TODO: change all routes under

Route::get('order/calculator', function (){
    return view('order.calculator');
})->name('order.calculator')->middleware('role:admin,client,guest');


Route::get('cancel_mailing/{order}/{token?}', 'Client\ClientController@cancelMailing')->name('cancel_mailing')->middleware('role:client,guest');
Route::get('confirm_mailing/{order}/{token?}', 'Client\ClientController@confirmMailing')->name('confirm_mailing')->middleware('role:client,guest');

Route::resource('order', 'OrderController', ['only' => ['show']]);

Route::group(['prefix' => 'brand', 'as' => 'brand.', 'namespace' => 'Equipment'], function () {
    Route::get('{equipment_type}', 'EquipmentController@index')->name('index')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::post('{equipment_type}', 'EquipmentController@index')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}', 'EquipmentController@show')->name('show')
        ->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}/review/create', 'EquipmentReviewController@create')
        ->name('review.create')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::get('{equipment_type}/{brand_slug}/review/{id}/edit', 'EquipmentReviewController@edit')
        ->name('review.edit')->where('equipment_type', '^(solar-panel|inverter)$');

    Route::resource('review', 'EquipmentReviewController', ['except' => [ 'create', 'edit', 'index' ]]);
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'role:admin'], function () {


    Route::get('portfolio/photo/minimize', 'MasterPortfolioController@minimizePhoto');
//    admin.order.index page request based filtering
    Route::post('order/photo/delete', 'OrderController@deletePhoto')->name('order.photo.delete');

    Route::get('order/activate/{id}', 'OrderController@activate')->name('order.activate');

    Route::post('order/attachment/upload', 'OrderController@attachmentUpload')->name('attachment.upload');

    Route::post('/order/attachment/upload/completed', 'OrderController@finishUploadSession')->name('attachment.upload.complete');
    
    Route::post('order', 'OrderController@index')->name('order.index.filter');

    Route::post('order/{id}/subcategory/change', 'OrderController@changeCategory')->name('order.category.change');

    Route::get('order/{id}/request', 'OrderController@requests')->name('order.request');

    Route::put('order/{id}/meta', 'OrderController@updateMeta')->name('order.update.meta');

    Route::resource('order', 'OrderController', [
        'except' => ['create', 'store', 'destroy']
    ]);

    Route::resource('request', 'OrderRequestController', [
        'only' => ['edit', 'update']
    ]);

    Route::resource('preorder', 'PreorderController', ['only' => ['index', 'update']]);


    Route::resource('client_email', 'ClientEmailController', ['only' => ['index', 'update']]);

    Route::get('client_catalog_list', 'ClientEmailController@showCatalog')->name('client_catalog_list');

    Route::put('client_catalog_list/{id}', 'ClientEmailController@updateCatalog')->name('update_catalog');

//      admin.equipment.index page request based filtering
    Route::resource('equipment', 'EquipmentController', ['only' => ['index']]);

    Route::group(['prefix' => 'equipment', 'as' => 'equipment.'], function () {
        Route::post('', 'EquipmentController@index')->name('index.filter');

        Route::get('create', 'EquipmentController@create')->name('create');

        Route::post('store', 'EquipmentController@store')->name('store');

app/Http/Controllers/Master/OrderController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller as Controller;
use App\Models\Order;
use App\Models\OrderRequest;
use App\Repositories\Criteria\Order\HomeSes;
use App\Repositories\Criteria\Order\InMastersRegions;
use App\Repositories\Criteria\Order\MasterList;
use App\Repositories\Criteria\Order\MasterListPrivate;
use App\Repositories\Criteria\RelationAttribute;
use App\Repositories\OrderRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{

    protected $orderRepository;

    public function __construct(OrderRepository $orderRepository)
    {
        $this->middleware('commission');

        $this->orderRepository = $orderRepository;
    }

    /**
     * Display a list of orders.
     *
     * @param  string $filter
     * @return \Illuminate\Http\Response
     */
    public function index($filter = null)
    {
        $master_id = Auth::user()->master->id;
        $master = Auth::user()->master;
        $this->orderRepository->pushCriteria(new MasterList($master_id));

        if($master->getSesTypes() == 'commercial_ses') {
            if($filter == 'region_filter_on') {
                $filter = 'commercial/region_filter_on';
            }
            else {
                $filter = 'commercial';
            }
        }
        else if($master->getSesTypes() == 'home_ses') {
            if($filter == 'region_filter_on') {
                $filter = 'home/region_filter_on';
            }
            else {
                $filter = 'home';
            }
        }
        if(!$this->orderRepository->validateUrlFilter($filter))
            abort(404);

        $filter = $this->orderRepository->decodeUrlFilter($filter);

        if(isset($filter['category']))
            $this->orderRepository->pushCriteria(new RelationAttribute('subcategory.category', 'slug', $filter['category']));

        if(isset($filter['subcategory']))
            $this->orderRepository->pushCriteria(new RelationAttribute('subcategory', 'slug', $filter['subcategory']));

        if(isset($filter['home']))
            $this->orderRepository->pushCriteria(new HomeSes('subcategory', 'slug', $filter['home']));

        if(isset($filter['region_filter_on']))
            $this->orderRepository->pushCriteria(new InMastersRegions($master_id));

        $orders = $this->orderRepository->paginate(20);

        return view('master.order.index', compact('orders', 'filter', 'master'));
    }

    /**
     * Display a list of orders where master selected as executor.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexPrivate()
    {
        $master_id = Auth::user()->master->id;

        $orders = $this->orderRepository->pushCriteria(new MasterListPrivate($master_id))->all();

        return view('master.order.private.index', compact('orders'));
    }

    /**
     * Display the specified order.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = $this->orderRepository->with(['subcategory.category', 'orderable', 'subcategory.category.request_price_types', 'status'])->findOrFail($id);

        if(Auth::user()->can('view', $order)){
            if(Auth::user()->can('own', $order))
                return redirect()->route('master.order.private.show', ['id' => $order->id]);

//            TODO: query in controller is not good (use request relation)
            $request = OrderRequest::with(['master' => function($master) {
                $master->withCount(['reviews', 'negative_reviews']);
            }, 'prices'])->where('master_id', Auth::user()->master->id)->where('order_id', $order->id)->first();

            if(isset($request)) {
                return view('master.request.show', compact('order', 'request'));
            } else {
                return view('master.request.create', compact('order'));
            }
        }else{
            return 'Проект закрито';
        }
    }

    /**
     * Display the specified order where master selected as executor.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showPrivate($id)
    {
        $order = Order::with([
            'subcategory.category',
            'orderable.order.region',
            'subcategory.category.request_price_types',
            'status',
            'region'
        ])->findOrFail($id);

        if(Auth::user()->can('own', $order)) {
            return view('master.order.private.show', compact('order'));
        } else {
            return 'Доступ заблоковано';
        }
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Client\NbuClient;
use App\Repositories\Criteria\CriteriaHelper;
use App\Repositories\Criteria\Attribute;
use App\Repositories\Criteria\RelationAttribute;
use App\Repositories\Criteria\Order\AdminList;
use App\Repositories\OrderRepository;
use App\Repositories\MasterRepository;
use Illuminate\Http\Request;
use App\Models\Order;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{

    /**
     * @var OrderRepository
     */
    protected $orderRepository;

    /**
     * @var MasterRepository
     */
    protected $masterRepository;


    public function __construct(OrderRepository $orderRepository, MasterRepository $masterRepository)
    {
        $this->orderRepository = $orderRepository;
        $this->masterRepository = $masterRepository;
    }

    /**
     * Display the specified order.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = $this->orderRepository->with(['subcategory.category', 'orderable', 'requests.master.user', 'status'])->findOrFail($id);

        if (!Auth::check() && $order->status->slug != 'done') {
            abort(404);
        }

        return view('guest.order.show', compact('order'));
    }
}

app/Http/Controllers/Partner/OrderController.php
<?php

namespace App\Http\Controllers\Partner;

use App\Http\Controllers\Controller as Controller;
use App\Repositories\Contracts\OrderRepositoryInterface;
use Illuminate\Http\Request;

class OrderController extends Controller
{

    protected $orderRepository;

    public function __construct(OrderRepositoryInterface $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    /**
     * Display a list of orders.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new order.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created order in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified order.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified order.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified order in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified order from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/order/station-info-category/station-commercial.blade.php
@extends('order.station-info')

@section('station-class', 'network-station roof-station')

@section('station-methods-calc')
    <p class="info">А розрахувати необхідну потужність можна декількома способами:</p>
    <ol class="calculation-info">
        <li><span>1.</span> в залежності від того, яку суму ви можете інвестувати;</li>
        <li><span>2.</span> в залежності від площі @yield('station-area-type'), де ви можете розмістити станцію.</li>
    </ol>
    <p class="info">Скористайтеся калькулятором нижче, щоб приблизно зрозуміти яка потужність станції вам потрібна:</p>
@endsection

@section('station-power')
    <div class="station-power-block ">
        <div class="enter-other-power">
            <p class="title">Потужність станції:</p>
        </div>

        @yield('slider-power')
        <!-- /.slider-block -->

        <!-- /.title -->

        <!-- /.info -->
        <div class="params-block">
            <div class="param-item">
                @yield('station-type-photo')
                <p>Необхідна площа @yield('station-area-type'):
                    <a class="tooltip-btn">
                        ?
                        <span class="tooltip">@yield('tooltip-text')</span>
                        <!-- /.tooltip -->
                    </a>
                </p>
                <strong><b class="square-text">25 га</b></strong>
            </div>
            <!-- /.param-item -->
            <div class="param-item">
                <img src="{{ asset('images/price_icon.png') }}" alt="image">
                <p>
                    Приблизна вартість станції:
                    <a class="tooltip-btn">
                        ?
                        <span class="tooltip">Вартість вказана за станцію "Під ключ" - тобто із всіма проектами, дозволами та підключенням.<br>
Зверніть увагу! Оскільки в процесі роботи станції ПДВ буде компенсовано, то для розрахунку терміну окупності потрібно від цієї суми відняти 17%.</span>
                        <!-- /.tooltip -->
                    </a>
                </p>
                <strong>$
                    <span class="min-cost" style="display: inline; font-weight: 600; font-size: 22px; color: #32394a;">13 000</span>
                    - <span class="max-cost" style="display: inline; font-weight: 600; font-size: 22px; color: #32394a;">17 000</span></strong>
            </div>
            <!-- /.param-item -->
            <div class="param-item">
                <img src="{{ asset('images/generation.png') }}" alt="image">
                <p>
                    Приблизна річна генерація:
                </p>
                <strong class="year-generation">17 тис. кВт&middot;год</strong>
            </div>
            <!-- /.param-item -->
            <div class="param-item">
                <img src="{{ asset('images/income.png') }}" alt="image">
                <p>
                    Максимальний дохід за рік:
                </p>
                <strong class="max-income">&euro; 2 000</strong>
            </div>
            <!-- /.param-item -->
        </div>
        <!-- /.params-block -->
        @yield('alert')
        <!-- /.alert alert-danger -->
    </div>
@endsection

@section('station-max-income')
    <div class="param-item">
        <img src="{{ asset('images/income.png') }}" alt="image">
        <p>
            Максимальний дохід за рік:
        </p>
        <strong>$2 000</strong>
        <span>(Якщо власне споживання = 0)</span>
    </div>
@endsection

resources/views/order/station-info-category/station-home.blade.php
@extends('order.station-info')

@section('station-power')
    <div class="station-power-block ">
        <p class="title">Потужність станції:</p>
        <!-- /.title -->
        @yield('slider-power')
        <!-- /.slider-block -->
        @yield('station-batteries-capacity')
        <!-- /.info -->
        <div class="params-block">
            <div class="param-item">
                <img src="{{ asset('images/house.png') }}" alt="image">
                <p>Необхідна площа даху:
                    <a class="tooltip-btn">
                        ?
                        <span class="tooltip">
                      Панелі можна встановлювати на незатінену частину даху, яка повернута на Південь, на Південний Схід,
                            або на Південний Захід. Встановлювати панелі з орієнтацією на Північ - недоцільно. <br>
                            Окрім даху, панелі можна розміщувати на господарські приміщення, на гаражі, на прибудинкову територію, на огорожу, тощо
                    </span>
                        <!-- /.tooltip -->
                    </a>
                </p>
                <strong><b class="square-text">30</b> м<sup>2</sup></strong>
            </div>
            <!-- /.param-item -->
            <div class="param-item">
                <img src="{{ asset('images/price_icon.png') }}" alt="image">
                <p>
                    Приблизна вартість станції:
                </p>
                <strong>$
                    <span class="min-cost" style="display: inline; font-weight: 600; font-size: 22px; color: #32394a;">13 000</span>
                    - <span class="max-cost" style="display: inline; font-weight: 600; font-size: 22px; color: #32394a;">17 000</span></strong>
            </div>
            <!-- /.param-item -->
            <div class="param-item">
                <img src="{{ asset('images/generation.png') }}" alt="image">
                <p>
                    Приблизна річна генерація:
                </p>
                <strong class="year-generation">17 тис. кВт&middot;год</strong>
            </div>
            <!-- /.param-item -->
        @yield('station-max-income')
        <!-- /.param-item -->
        </div>
        <!-- /.params-block -->
        @yield('alert')
        <!-- /.alert alert-danger -->
    </div>
@endsection

@section('station-faq-info')
    <div class="station-info-block left-image right-arrow">
        <div class="station-info-img">
            <img src="{{ asset('images/accum-img.png') }}" alt="image">
        </div>
        <!-- /.station-info-img -->
        <h2>Чи потрібні вам акумулятори?</h2>
        <p>
            У 90% випадків - українцям <b> не потрібні</b> акумулятори для домашніх сонячних станцій. <br> <br>

            Сонячна станція з акумуляторами коштує на <b>30-40% дорожче.</b> <br> <br>

            Акумулятори доцільно встановлювати у двох випадках:

        </p>
        <ul class="styled-list">
            <li>
                <span class="list-number">1</span>
                <!-- /.list-number -->
                якщо у вас зовсім нема підключення до електромережі, і за підключення до мережі місцевий РЕМ
                просить тисячі доларів. В такому випадку вигідно встановити <a href="{{ route('assistant.autonomous') }}">автономну сонячну
                    електростанцію</a>
                з акумуляторами.
            </li>
            <li>
                <span class="list-number">2</span>
                якщо у вас дуже(!) проблемна електромережа і дуже часті відключення ел.енергії.
                В такому випадку вам доцільно встановити систему акумулювання енергії.
                При цьому не обов’язково тоді встановлювати сонячні панелі - достатньо лише акумуляторів та
                інвертора.
            </li>
        </ul>
        <!-- /.styled-list -->
        @yield('station-link')
    </div>
@endsection

@section('landing-benefits')
    <div class="station-info-block right-image left-arrow">
        <div class="station-info-img">
            <img src="{{ asset('images/document_img.png') }}" alt="image">
        </div>
        <!-- /.station-info-img -->
        <h2>Чи є в Україні програми по пільговому кредитуванню
            або фінансуванню будівництва сонячних станцій?</h2>
        <div class="hidden-text">
            <p>
                Станом на листопад 2017 року в Україні діють такі прогами підтримки будівництва сонячних станцій:
                <br><br>
                <i>1. у Житомирській обл. місцевий бюджет повертає 20% вартості будівництва сонячної електростанції</i>
                <br><br>
                <i>2. у Львівській обл. місцевий бюджет повертає від 5 до 20% річних за кредитами, залученими на будівництво сонячних електростанцій</i>
                <br><br>
                Окрім цього, Укргазбанк видає "безвідсоткові" кредити на купівлю сонячних станцій. Але варто
                зазначити, що сплата відсотків лягає на плечі монтажника, тому якщо ви купуватимете станцію з
                "безвідсотковим" кредитом, то базова вартість станції буде відразу вищою на 10-15%, у порівнянні з
                купівлею без кредита.
                <br><br>
                Якщо вас цікавить кредитування, вам потрібно оговорити це питання із монтажниками - вони часто
                співпрацюють з різними банками, де можуть запропонувати не гірші умови, ніж в Укргазбанку.
                <br><br>
                Варто пам'ятати, що в Україні діє один із найвищих в Європі “зелених” тарифів, завдяки якому будівництво СЕС є вигідною інвестицією навіть без пільгового кредитування.

            </p>
        </div>
        <!-- /.hidden-text -->
        <a href="#" class="show-more">Показати більше</a>

    </div>
@endsection

{{--@section('station-equipment')--}}
    {{--<li>--}}
        {{--<span class="list-number">3</span>--}}
        {{--Для гібридних станцій варто окремо також згадати про <b>акумулятори.</b>--}}
        {{--Їхня вартість зараз становить близько 200 у.о. за 1 кВт-год.--}}
        {{--Якщо ви вирішили купувати акумулятори, то краще брати літієві.--}}
        {{--Вони трохи дорожчі, але строк служби у них значно більший, ніж у кислотних чи гелевих.--}}
        {{--Як варіант, ви можете купити вживаний акумулятор від електромобіля - на даний момент це--}}
        {{--найдешевший варіант для акумулювання енергії.--}}
    {{--</li>--}}
{{--@endsection--}}